#!/usr/bin/env python3
"""Generate quartz/components/scripts/sealcarver/sigils.gen.ts from sigils/.

Each sigil becomes {w, h, body}: viewBox dimensions plus inner markup with
stroke:black rewritten to currentColor so the on-screen seal follows the site
theme. Exports rewrite currentColor back to #000 (compose.ts). Bodies keep
their original per-path stroke-widths; compose.ts rescales proportionally.
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SIG = ROOT / "sigils"
OUT = ROOT / "quartz/components/scripts/sealcarver/sigils.gen.ts"
CATEGORIES = ["elements", "functions", "modifiers", "targets", "triggers"]


def inner(svg_text: str) -> str:
    start = svg_text.index(">", svg_text.index("<svg")) + 1
    return svg_text[start : svg_text.rindex("</svg>")].strip()


def main() -> None:
    entries = []
    for cat in CATEGORIES:
        d = SIG / cat
        if not d.is_dir():
            continue  # triggers/ may not exist until the extraction task lands
        for f in sorted(d.glob("*.svg")):
            text = f.read_text()
            vb = re.search(r'viewBox="([\d.\s-]+)"', text).group(1).split()
            body = inner(text).replace("stroke:black", "stroke:currentColor")
            entries.append((f"{cat}/{f.stem}", float(vb[2]), float(vb[3]), body))
    lines = [
        "// AUTO-GENERATED by scripts/generate-sigil-module.py -- DO NOT EDIT.",
        "// Source art: Codex of Arcane Arts, Roc Humet Vidal, CC-BY 4.0 (sigils/LICENSE.md).",
        "export interface SigilAsset { w: number; h: number; body: string }",
        "export const SIGILS: Record<string, SigilAsset> = {",
    ]
    for key, w, h, body in entries:
        lines.append(f"  {json.dumps(key)}: {{ w: {w}, h: {h}, body: {json.dumps(body)} }},")
    lines.append("}\n")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} with {len(entries)} sigils")


if __name__ == "__main__":
    main()
